<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('datas')->insert([
            [
                'kecamatan' => 'Fatuleu',
                'jumlah_kasus' => 591,
                'info' => 'info-fatuleu',
                'latitude' => '-9.9975499',
                'longitude' => '123.9300209',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Kupang Timur',
                'jumlah_kasus' => 576,
                'info' => 'ingo-kupang-timur',
                'latitude' => '-10.0880582',
                'longitude' => '123.7530685',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Amarasi Barat',
                'jumlah_kasus' => 456,
                'info' => 'info-amarasi-barat',
                'latitude' => '-10.2953411',
                'longitude' => '123.6575829',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Kupang Tengah',
                'jumlah_kasus' => 389,
                'info' => 'info-kupang-tengah',
                'latitude' => '-10.1358114',
                'longitude' => '123.6737537',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Amabi Oefeto',
                'jumlah_kasus' => 412,
                'info' => 'info-amabi-oefeto',
                'latitude' => '-10.0932342',
                'longitude' => '123.8345678',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Taebenu',
                'jumlah_kasus' => 350,
                'info' => 'info-taebenu',
                'latitude' => '-10.2323234',
                'longitude' => '123.7654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Sulamu',
                'jumlah_kasus' => 310,
                'info' => 'info-sulamu',
                'latitude' => '-10.1123456',
                'longitude' => '123.6543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Takari',
                'jumlah_kasus' => 290,
                'info' => 'info-takari',
                'latitude' => '-10.2212345',
                'longitude' => '123.5432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Nekamese',
                'jumlah_kasus' => 275,
                'info' => 'info-nekamese',
                'latitude' => '-10.3345678',
                'longitude' => '123.4321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Fatuleu Tengah',
                'jumlah_kasus' => 260,
                'info' => 'info-fatuleu-tengah',
                'latitude' => '-10.4456789',
                'longitude' => '123.3210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Molo',
                'jumlah_kasus' => 240,
                'info' => 'info-molo',
                'latitude' => '-10.5567890',
                'longitude' => '123.2109876',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Taebar',
                'jumlah_kasus' => 220,
                'info' => 'info-taebar',
                'latitude' => '-10.6678901',
                'longitude' => '123.1098765',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Semau',
                'jumlah_kasus' => 200,
                'info' => 'info-semau',
                'latitude' => '-10.7789012',
                'longitude' => '123.0987654',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Oesao',
                'jumlah_kasus' => 185,
                'info' => 'info-oesao',
                'latitude' => '-10.8890123',
                'longitude' => '123.0876543',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Naibonat',
                'jumlah_kasus' => 170,
                'info' => 'info-naibonat',
                'latitude' => '-10.9901234',
                'longitude' => '123.0765432',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Panite',
                'jumlah_kasus' => 150,
                'info' => 'info-panite',
                'latitude' => '-11.0012345',
                'longitude' => '123.0654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Oesena',
                'jumlah_kasus' => 130,
                'info' => 'info-oesena',
                'latitude' => '-11.1123456',
                'longitude' => '123.0543210',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Lelogama',
                'jumlah_kasus' => 120,
                'info' => 'info-lelogama',
                'latitude' => '-11.2234567',
                'longitude' => '123.0432109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Taebobor',
                'jumlah_kasus' => 110,
                'info' => 'info-taebobor',
                'latitude' => '-11.3345678',
                'longitude' => '123.0321098',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kecamatan' => 'Nunkolo',
                'jumlah_kasus' => 100,
                'info' => 'info-nunkolo',
                'latitude' => '-11.4456789',
                'longitude' => '123.0210987',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
